BrandysList/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('', RedirectView.as_view(url='/home/home/category/', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    #path('',views.index,name='index')
]

urlpatterns += (
    # urls for Category
    path('home/category/', views.CategoryListView.as_view(), name='home_category_list'),
    path('home/category/create/', views.CategoryCreateView.as_view(), name='home_category_create'),
    path('home/category/detail/<slug:slug>/', views.CategoryDetailView.as_view(), name='home_category_detail'),
    path('home/category/update/<slug:slug>/', views.CategoryUpdateView.as_view(), name='home_category_update'),
)

urlpatterns += (
    # urls for ServiceProvider
    path('home/serviceprovider/', views.ServiceProviderListView.as_view(), name='home_serviceprovider_list'),
    path('home/serviceprovider/create/', views.ServiceProviderCreateView.as_view(), name='home_serviceprovider_create'),
    path('home/serviceprovider/detail/<slug:slug>/', views.ServiceProviderDetailView.as_view(), name='home_serviceprovider_detail'),
    path('home/serviceprovider/update/<slug:slug>/', views.ServiceProviderUpdateView.as_view(), name='home_serviceprovider_update'),
)

urlpatterns += (
    # urls for Service
    path('home/service/', views.ServiceListView.as_view(), name='home_service_list'),
    path('home/service/create/', views.ServiceCreateView.as_view(), name='home_service_create'),
    path('home/service/detail/<slug:slug>/', views.ServiceDetailView.as_view(), name='home_service_detail'),
    path('home/service/update/<slug:slug>/', views.ServiceUpdateView.as_view(), name='home_service_update'),
)

urlpatterns += (
    path('home/form/', views.AddressFormView.as_view(template_name='home/form_1.html'), name='form_1'),
)

home/models.py
#models.py
from django.urls import reverse
from django_extensions.db.fields import AutoSlugField
from django.db.models import CharField
from django.db.models import UUIDField
from django_extensions.db.fields import AutoSlugField
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth import get_user_model
from django.contrib.auth import models as auth_models
from django.db import models as models
from django_extensions.db import fields as extension_fields
from phone_field import PhoneField
from django.core.validators import RegexValidator
from django.contrib.gis.db.models import PointField
from django.contrib.gis.geos import Point
from geopy.geocoders import Nominatim
import uuid


##########################
#        Category
##########################
class Category(models.Model):

    # Fields
    name = models.CharField(max_length=255)
    slug = extension_fields.AutoSlugField(populate_from='name', blank=True)

    class Meta:
        ordering = ('-pk',)
        verbose_name_plural = "categories"

    def __unicode__(self):
        return u'%s' % self.slug

    def get_absolute_url(self):
        return reverse('home_category_detail', args=(self.slug,))


    def get_update_url(self):
        return reverse('home_category_update', args=(self.slug,))

    def __str__(self):
        return self.name


##########################
#    Service Provider
##########################
class ServiceProvider(models.Model):

    # Fields
    name = models.CharField(max_length=255)
    contact_name = models.CharField(max_length=100)
    slug = extension_fields.AutoSlugField(populate_from='name', blank=True)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)

    #Contact Fields
    phone_number = PhoneField(blank=True, help_text='Provider Phone Number')
    email = models.EmailField(max_length=70, blank=True)
    website = models.URLField(max_length=250)
    description = models.TextField(blank=True, null=True)

    # Relationship Fields
    services = models.ManyToManyField(
        'home.Service',
        related_name="serviceproviders", 
    )

    class Meta:
        ordering = ('-pk',)

    def __unicode__(self):
        return u'%s' % self.slug

    def get_absolute_url(self):
        return reverse('home_serviceprovider_detail', args=(self.slug,))


    def get_update_url(self):
        return reverse('home_serviceprovider_update', args=(self.slug,))

    def __str__(self):
        return self.name


##########################
#        Address
##########################
STATES = (
    ('AL', 'Alabama'),
    ('AK', 'Alaska'),
    ('AZ', 'Arizona'),
    ('AR', 'Arkansas'),
    ('CA', 'California'),
    ('CO', 'Colorado'),
    ('CT', 'Connecticut'),
    ('DE', 'Delaware'),
    ('FL', 'Florida'),
    ('GA', 'Georgia'),
    ('HI', 'Hawaii'),
    ('ID', 'Idaho'),
    ('IL', 'Illinois'),
    ('IN', 'Indiana'),
    ('IA', 'Iowa'),
    ('KS', 'Kansas'),
    ('KY', 'Kentucky'),
    ('LA', 'Louisiana'),
    ('ME', 'Maine'),
    ('MD', 'Maryland'),
    ('MA', 'Massachusetts'),
    ('MI', 'Michigan'),
    ('MN', 'Minnesota'),
    ('MS', 'Mississippi'),
    ('MO', 'Missouri'),
    ('MT', 'Montana'),
    ('NE', 'Nebraska'),
    ('NV', 'Nevada'),
    ('NH', 'New Hampshire'),
    ('NJ', 'New Jersey'),
    ('NM', 'New Mexico'),
    ('NY', 'New York'),
    ('NC', 'Nort Carolina'),
    ('ND', 'North Dakota'),
    ('OH', 'Ohio'),
    ('OK', 'Oklahoma'),
    ('OR', 'Oregon'),
    ('PA', 'Pennsylvania'),
    ('RI', 'Rhode Island'),
    ('SC', 'South Carolina'),
    ('SD', 'South Dakota'),
    ('TN', 'Tennessee'),
    ('TX', 'Texas'),
    ('UT', 'Utah'),
    ('VT', 'Vermont'),
    ('VA', 'Virginia'),
    ('WA', 'Washington'),
    ('WV', 'West Virginia'),
    ('WI', 'Wisconsin'),
    ('WY', 'Wyoming'),
)
zip_validator = RegexValidator(r'^[0-9]{5}?$', 'Only 5 digit numbers allowed.')
geolocator = Nominatim(user_agent="home")
class Address(models.Model):
    location = PointField(srid=4326, geography=True, blank=True, null=True)
    #long = models.FloatField()
    #lat = models.FloatField()
    street = models.TextField()
    city = models.TextField()
    state = models.CharField(max_length=2, choices=STATES)
    zip_code = models.CharField(max_length=5, validators=[zip_validator])

    # Relationship Fields
    service_provider = models.OneToOneField(
        ServiceProvider,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name='address',
    )

    def save(self, *args, **kwargs):
        if not self.location:
            addr = self.street + ' ' + self.city + ' ' + self.state + ' ' + self.zip_code
            provider_point = geolocator.geocode(addr)
            self.location = Point(provider_point.longitude, provider_point.latitude)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "addresses"

    def __str__(self):
        return self.street



##########################
#     Provider Hours
##########################
WEEKDAYS = [
  (1, "Monday"),
  (2, "Tuesday"),
  (3, "Wednesday"),
  (4, "Thursday"),
  (5, "Friday"),
  (6, "Saturday"),
  (7, "Sunday"),
]
class ProviderHours(models.Model):

    # Fields
    weekday = models.IntegerField(
        choices=WEEKDAYS
    )

    # Relationship Fields
    service_provider = models.ForeignKey(
        ServiceProvider,
        on_delete=models.CASCADE,
        related_name="hours"
    )
    
    from_hour = models.TimeField(null=True)
    to_hour = models.TimeField(null=True)
    available_by_appt = models.BooleanField(default=True)


##########################
#       Service
##########################
class Service(models.Model):

    # Fields
    name = models.CharField(max_length=255)
    slug = extension_fields.AutoSlugField(populate_from='name', blank=True)

    # Relationship Fields
    Category = models.ForeignKey(
        'home.Category',
        on_delete=models.CASCADE, 
        related_name="services", 
    )

    class Meta:
        ordering = ('-pk',)

    def __unicode__(self):
        return u'%s' % self.slug

    def get_absolute_url(self):
        return reverse('home_service_detail', args=(self.slug,))

    def get_update_url(self):
        return reverse('home_service_update', args=(self.slug,))

    def __str__(self):
        return self.name

home/forms.py
from django import forms
from .models import Category, ServiceProvider, Service, Address
from django.core.validators import RegexValidator

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']


class ServiceProviderForm(forms.ModelForm):
    class Meta:
        model = ServiceProvider
        fields = ['name', 'id', 'services']


class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ['name', 'Category']


STATES = (
    ('AL', 'Alabama'),
    ('AK', 'Alaska'),
    ('AZ', 'Arizona'),
    ('AR', 'Arkansas'),
    ('CA', 'California'),
    ('CO', 'Colorado'),
    ('CT', 'Connecticut'),
    ('DE', 'Delaware'),
    ('FL', 'Florida'),
    ('GA', 'Georgia'),
    ('HI', 'Hawaii'),
    ('ID', 'Idaho'),
    ('IL', 'Illinois'),
    ('IN', 'Indiana'),
    ('IA', 'Iowa'),
    ('KS', 'Kansas'),
    ('KY', 'Kentucky'),
    ('LA', 'Louisiana'),
    ('ME', 'Maine'),
    ('MD', 'Maryland'),
    ('MA', 'Massachusetts'),
    ('MI', 'Michigan'),
    ('MN', 'Minnesota'),
    ('MS', 'Mississippi'),
    ('MO', 'Missouri'),
    ('MT', 'Montana'),
    ('NE', 'Nebraska'),
    ('NV', 'Nevada'),
    ('NH', 'New Hampshire'),
    ('NJ', 'New Jersey'),
    ('NM', 'New Mexico'),
    ('NY', 'New York'),
    ('NC', 'Nort Carolina'),
    ('ND', 'North Dakota'),
    ('OH', 'Ohio'),
    ('OK', 'Oklahoma'),
    ('OR', 'Oregon'),
    ('PA', 'Pennsylvania'),
    ('RI', 'Rhode Island'),
    ('SC', 'South Carolina'),
    ('SD', 'South Dakota'),
    ('TN', 'Tennessee'),
    ('TX', 'Texas'),
    ('UT', 'Utah'),
    ('VT', 'Vermont'),
    ('VA', 'Virginia'),
    ('WA', 'Washington'),
    ('WV', 'West Virginia'),
    ('WI', 'Wisconsin'),
    ('WY', 'Wyoming'),
)

SORT_DISTANCES = (
    ('Any', 'Any Distance'),
    ('5', '5 Miles'),
    ('10', '10 Miles'),
    ('20', '20 Miles'),
    ('50', '50 Miles')
)

class AddressForm(forms.Form):
    zip_validator = RegexValidator(r'^[0-9]{5}?$', 'Only 5 digit numbers allowed.')
    email = forms.EmailField()
    address = forms.CharField(
        label='Address',
        widget=forms.TextInput(attrs={'placeholder': '1234 Main St'})
    )

    city = forms.CharField()
    state = forms.ChoiceField(choices=STATES)
    zip_code = forms.CharField(max_length=5,validators=[zip_validator], label='Zip Code')
    sort_distance = forms.ChoiceField(choices=SORT_DISTANCES, label='Sort Distance')
    

home/views.py
# pylint: disable=unused-wildcard-import
# pylint: disable=wildcard-import
# pylint: disable=missing-docstring
# pylint: disable=too-many-ancestors
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.gis.db.models.functions import Distance
from django.contrib.gis.geos import Point
from django.contrib.gis.measure import D
from django.contrib.gis.geos import *
from django.views.generic import DetailView, ListView, UpdateView, CreateView, FormView
from django.urls import reverse_lazy
from geopy.geocoders import Nominatim
from .models import Category, ServiceProvider, Service
from .forms import CategoryForm, ServiceProviderForm, ServiceForm, AddressForm

# Create your views here.

def index(request):
    context = {}
    return render(request, 'home/index.html', context)



class CategoryListView(ListView):
    model = Category


class CategoryCreateView(CreateView):
    model = Category
    form_class = CategoryForm


class CategoryDetailView(DetailView):
    model = Category


class CategoryUpdateView(UpdateView):
    model = Category
    form_class = CategoryForm

geolocator = Nominatim(user_agent="home")
class ServiceProviderListView(ListView):
    model = ServiceProvider

    def get_queryset(self):
        result = super(ServiceProviderListView, self).get_queryset()
        
        sesh = self.request.session
        user_geolocation = geolocator.geocode(sesh['address'] + ' ' + sesh['city'] + ' ' + sesh['state'] + ' ' + sesh['zip'])
        user_location = Point(user_geolocation.longitude, user_geolocation.latitude, srid=4326)
        if sesh['sort_distance'] == 'Any':
            miles = 1000
        else:
            miles = sesh['sort_distance']
        #result = ServiceProvider.objects.annotate(distance=Distance("address__location", user_location)).order_by("distance")
        result = ServiceProvider.objects.filter(address__location__distance_lte=(user_location, D(mi=miles))).annotate(distance=Distance("address__location", user_location)).order_by("distance")
        #result = ServiceProvider.objects.filter(location__distance_lte=(user_location, D(50000))).annotate(distance=Distance("address__location", user_location)).order_by("distance")
        return result

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context        
        context = super().get_context_data(**kwargs)
        #context['service'] = self.request.GET.get('service')
        context['address'] = self.request.session['address']
        context['service'] = self.request.session['service']
        context['zip'] = self.request.session['zip']
        context['state'] = self.request.session['state']
        context['sort_distance'] = self.request.session['sort_distance']
        return context


class ServiceProviderCreateView(CreateView):
    model = ServiceProvider
    form_class = ServiceProviderForm


class ServiceProviderDetailView(DetailView):
    model = ServiceProvider


class ServiceProviderUpdateView(UpdateView):
    model = ServiceProvider
    form_class = ServiceProviderForm


class ServiceListView(ListView):
    model = Service


class ServiceCreateView(CreateView):
    model = Service
    form_class = ServiceForm

    


class ServiceDetailView(DetailView):
    model = Service

class ServiceUpdateView(UpdateView):
    model = Service
    form_class = ServiceForm


STATES = (
    ('AL', 'Alabama'),
    ('AK', 'Alaska'),
    ('AZ', 'Arizona'),
    ('AR', 'Arkansas'),
    ('CA', 'California'),
    ('CO', 'Colorado'),
    ('CT', 'Connecticut'),
    ('DE', 'Delaware'),
    ('FL', 'Florida'),
    ('GA', 'Georgia'),
    ('HI', 'Hawaii'),
    ('ID', 'Idaho'),
    ('IL', 'Illinois'),
    ('IN', 'Indiana'),
    ('IA', 'Iowa'),
    ('KS', 'Kansas'),
    ('KY', 'Kentucky'),
    ('LA', 'Louisiana'),
    ('ME', 'Maine'),
    ('MD', 'Maryland'),
    ('MA', 'Massachusetts'),
    ('MI', 'Michigan'),
    ('MN', 'Minnesota'),
    ('MS', 'Mississippi'),
    ('MO', 'Missouri'),
    ('MT', 'Montana'),
    ('NE', 'Nebraska'),
    ('NV', 'Nevada'),
    ('NH', 'New Hampshire'),
    ('NJ', 'New Jersey'),
    ('NM', 'New Mexico'),
    ('NY', 'New York'),
    ('NC', 'Nort Carolina'),
    ('ND', 'North Dakota'),
    ('OH', 'Ohio'),
    ('OK', 'Oklahoma'),
    ('OR', 'Oregon'),
    ('PA', 'Pennsylvania'),
    ('RI', 'Rhode Island'),
    ('SC', 'South Carolina'),
    ('SD', 'South Dakota'),
    ('TN', 'Tennessee'),
    ('TX', 'Texas'),
    ('UT', 'Utah'),
    ('VT', 'Vermont'),
    ('VA', 'Virginia'),
    ('WA', 'Washington'),
    ('WV', 'West Virginia'),
    ('WI', 'Wisconsin'),
    ('WY', 'Wyoming'),
)

class AddressFormView(FormView):
    form_class = AddressForm
    success_url = reverse_lazy('home_serviceprovider_list')

    def form_valid(self, form):
        self.request.session['address'] = form.cleaned_data['address']
        self.request.session['city'] = form.cleaned_data['city']
        self.request.session['state'] = form.cleaned_data['state']
        self.request.session['zip'] = form.cleaned_data['zip_code']
        self.request.session['sort_distance'] = form.cleaned_data['sort_distance']
        self.request.session['service'] = self.request.GET.get('service')
        return redirect('home_serviceprovider_list')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context['service'] = self.request.GET.get('service')
        return context

home/templates/home/base2.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Brandy's List2</title>
  </head>
  <body>
    <h1>Brandy's List</h1>
    {% block content %}
    {% endblock %}
    {% comment %} <img src="{% static "Brandy.jpg" %}" class="rounded" alt="Brandy"> {% endcomment %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

home/templates/home/category_detail.html
{% extends 'home/basealt.html' %}

{% block content %}

{% if category.services.all %}
    <h2>{{category.name}} Services</h2>
    <table class="table table-bordered table-condensed table-hover">
        <thead>
          <tr>
            <th>Service</th>
          </tr>
        </thead>
        <tbody>
            {% for service in category.services.all|dictsort:"name" %}
            <tr class="table-row" data-href="{% url 'form_1' %}?service={{service.name}}" >
                <td>{{service.name}}</td>
            </tr>                  
            {% endfor %}
        </tbody>
    </table>
{% else %}
  <p>There are no services for this category.</p>
{% endif %}
{% endblock content %}
   
        

home/templates/home/category_list.html
{% extends 'home/basealt.html' %}
{% block content %}

{% if category_list %}
    
    <div class="row">
    {% for category in category_list|dictsort:"name" %}
          <div class="col-md-4">
            <h2>{{category.name}}</h2>
            <p>My category </p>
            <p><a class="btn btn-secondary" href="{{ category.get_absolute_url }}" role="button">View Category »</a></p>
          </div>
    {% endfor %}
    </div>


{% else %}
  <p>There are no categories available.</p>
{% endif %}   
        
{% endblock content %}

home/templates/home/form_1.html
{% extends 'home/basealt.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h2>{{service}}</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-6 mb-0">
        {{ form.email|as_crispy_field }}
      </div>
    </div>
    {{ form.address|as_crispy_field }}
    <div class="form-row">
      <div class="form-group col-md-4 mb-0">
        {{ form.city|as_crispy_field }}
      </div>
      <div class="form-group col-md-4 mb-0">
        {{ form.state|as_crispy_field }}
      </div>
      <div class="form-group col-md-2 mb-0">
        {{ form.zip_code|as_crispy_field }}
      </div>
      <div class="form-group col-md-2 mb-0">
        {{ form.sort_distance|as_crispy_field }}
      </div>
    </div>
    <button type="submit" class="btn btn-primary">View matching Service Providers</button>
  </form>
{% endblock %}

home/templates/home/index.html
{{% extends 'base.html' %}}

home/templates/home/service_detail.html
{% extends 'home/basealt.html' %}

{% block content %}

<h1> {{ service.Category }} : {{service.name}} </h1>

{% endblock content %}

home/templates/home/serviceprovider_detail.html
{% extends 'home/basealt.html' %}
{% load staticfiles%}
{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body{
    background: -webkit-linear-gradient(left, #3931af, #00c6ff);
}
.emp-profile{
    padding: 3%;
    margin-top: 3%;
    margin-bottom: 3%;
    border-radius: 0.5rem;
    background: #fff;
}
.profile-img{
    text-align: center;
}
.profile-img img{
    width: 70%;
    height: 100%;
}
.profile-img .file {
    position: relative;
    overflow: hidden;
    margin-top: -20%;
    width: 70%;
    border: none;
    border-radius: 0;
    font-size: 15px;
    background: #212529b8;
}
.profile-img .file input {
    position: absolute;
    opacity: 0;
    right: 0;
    top: 0;
}
.profile-head h5{
    color: #333;
}
.profile-head h6{
    color: #0062cc;
}
.profile-edit-btn{
    border: none;
    border-radius: 1.5rem;
    width: 70%;
    padding: 2%;
    font-weight: 600;
    color: #6c757d;
    cursor: pointer;
}
.proile-rating{
    font-size: 12px;
    color: #818182;
    margin-top: 5%;
}
.proile-rating span{
    color: #495057;
    font-size: 15px;
    font-weight: 600;
}
.profile-head .nav-tabs{
    margin-bottom:5%;
}
.profile-head .nav-tabs .nav-link{
    font-weight:600;
    border: none;
}
.profile-head .nav-tabs .nav-link.active{
    border: none;
    border-bottom:2px solid #0062cc;
}
.profile-work{
    padding: 14%;
    margin-top: -15%;
}
.profile-work p{
    font-size: 12px;
    color: #818182;
    font-weight: 600;
    margin-top: 10%;
}

.profile-work2 p{
    text-decoration: none;
    color: #495057;
    font-weight: 600;
    font-size: 14px;
    margin-top: 5%;
}
.profile-work a{
    text-decoration: none;
    color: #495057;
    font-weight: 600;
    font-size: 14px;
}
.profile-work ul{
    list-style: none;
}
.profile-tab label{
    font-weight: 600;
}
.profile-tab p{
    font-weight: 600;
    color: #0062cc;
}
.provider-desription p{
    color: #495057;
    padding: 0;
}
.checked {
  color: orange;
}

</style>
<div class="container emp-profile">
            <form method="post">
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-img">
                             <img src="{% static "Brandy.jpg" %}">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="profile-head">
                                    <h1>
                                        {{serviceprovider.name}}
                                    </h1>
                                    <h6>
                                        Web Developer and Designer
                                    </h6>
                                    <p class="proile-rating">RATING : </p>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star"></span>
                                    <span class="fa fa-star"></span>
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">About</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Timeline</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-work">
                            <p>COMPANY CONTACT</p>
                            <div class="profile-work2">
                                <p>Name : {{serviceprovider.contact_name }}</p>
                                <p>Phone #: {{serviceprovider.phone_number }}</p>
                                <p>Email: {{serviceprovider.email }}</p>
                                <p>{{serviceprovider.address.street }}</p>
                            </div>
                            <p>HOURS</p>
                            <div class="profile-work2">
                                <p>Web Designer</p>
                                <p>Web Developer</p>
                                <p>WordPress</p>
                                <p>WooCommerce</p>
                                <p>PHP, .Net</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="tab-content profile-tab" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                        <div class="row">
                                            <div class ="provider-desription">
                                                <p>{{serviceprovider.description}}</p> 
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Name</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>Kshiti Ghelani</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Email</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>kshitighelani@gmail.com</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Phone</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>123 456 7890</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Profession</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>Web Developer and Designer</p>
                                            </div>
                                        </div>
                            </div>
                            <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                                        
                                        {% for hours in serviceprovider.hours.all%}
                                            <div class="row">
                                                <div class="col-md-4">
                                                    <label>{{hours.get_weekday_display}}</label>
                                                </div>
                                                <div class="col-md-8">
                                                    <p>{{hours.from_hour}} - {{hours.to_hour}}</p>
                                                </div>
                                            </div>
                                        {% endfor %}
                                        
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Hourly Rate</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>10$/hr</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Total Projects</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>230</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>English Level</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>Expert</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Availability</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>6 months</p>
                                            </div>
                                        </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <label>Your Bio</label><br/>
                                        <p>Your detail description</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>           
        </div>

{% endblock content %}